import type { WidgetDefinition } from '@/core/widget';
import type { QuotesSettings } from './types';

export const quotesManifest: WidgetDefinition<QuotesSettings> = {
  id: 'quotes',
  nameKey: 'widgets.quotes',
  descriptionKey: 'widgetDesc.quotes',
  version: '2.5.0',
  iconName: 'Quote',
  category: 'entertainment',
  surface: 'panel',
  size: {
    defaultW: 6,
    defaultH: 2,
    minW: 4,
    minH: 2,
  },
  settingsSchema: [
    {
      key: 'category',
      labelKey: 'Категория цитат',
      type: 'select',
      defaultValue: 'all',
      section: 'behavior',
      helperText: 'Тематическая подборка вдохновляющих высказываний',
      options: [
        { labelKey: 'Все категории', value: 'all' },
        { labelKey: 'Технологии и разработка', value: 'code' },
        { labelKey: 'Мудрость и философия', value: 'wisdom' },
        { labelKey: 'Мотивация и продуктивность', value: 'motivation' },
        { labelKey: 'Жизнь и творчество', value: 'life' },
      ],
    },
    {
      key: 'fontStyle',
      labelKey: 'Стиль типографики',
      type: 'segmented',
      defaultValue: 'serif',
      section: 'appearance',
      helperText: 'Классический книжный Serif или современный гротеск Sans',
      options: [
        { labelKey: 'Элегантный Serif', value: 'serif' },
        { labelKey: 'Современный Sans', value: 'sans' },
        { labelKey: 'Терминал Mono', value: 'mono' },
      ],
    },
    {
      key: 'textAlign',
      labelKey: 'Выравнивание текста',
      type: 'segmented',
      defaultValue: 'center',
      section: 'appearance',
      helperText: 'Расположение цитаты на карточке виджета',
      options: [
        { labelKey: 'По центру', value: 'center' },
        { labelKey: 'По левому краю', value: 'left' },
      ],
    },
    {
      key: 'showAuthor',
      labelKey: 'Показывать автора',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Отображение имени автора под текстом цитаты',
    },
    {
      key: 'showCopyButton',
      labelKey: 'Кнопка копирования цитаты',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Иконка быстрого копирования цитаты в буфер обмена',
    },
    {
      key: 'autoRefreshInterval',
      labelKey: 'Автосмена цитаты',
      type: 'select',
      defaultValue: 0,
      section: 'behavior',
      helperText: 'Периодичность автоматической смены цитаты (0 = только вручную)',
      options: [
        { labelKey: 'Только вручную (по клику)', value: 0 },
        { labelKey: 'Каждый час', value: 1 },
        { labelKey: 'Каждые 4 часа', value: 4 },
        { labelKey: 'Каждые 24 часа (Раз в день)', value: 24 },
      ],
    },
  ],
  load: () => import('./QuotesWidget').then((m) => ({ default: m.QuotesWidget })),
};
