import type { WidgetDefinition } from '@/core/widget';
import type { BookmarkSettings } from './types';

export const bookmarksManifest: WidgetDefinition<BookmarkSettings> = {
  id: 'bookmarks',
  nameKey: 'widgets.bookmarks',
  descriptionKey: 'widgetDesc.bookmarks',
  version: '3.1.0',
  iconName: 'Bookmark',
  category: 'productivity',
  surface: 'tiles',
  permissions: ['bookmarks'],
  size: {
    defaultW: 6,
    defaultH: 4,
    minW: 1,
    minH: 1,
  },
  settingsSchema: [
    {
      key: 'mode',
      labelKey: 'common.mode',
      type: 'select',
      defaultValue: 'folder',
      options: [
        { labelKey: 'Папка с сайтами', value: 'folder' },
        { labelKey: 'Одиночный сайт (1 сайт = 1 виджет)', value: 'single' },
        { labelKey: 'Папка с сайтами и вкладками', value: 'folder-tabs' },
      ],
    },
    {
      key: 'tileShape',
      labelKey: 'Форма закладок',
      type: 'select',
      defaultValue: 'rectangle-horizontal',
      options: [
        { labelKey: 'Прямоугольные горизонтальные (Карточки)', value: 'rectangle-horizontal' },
        { labelKey: 'Квадратные (Speed Dial / iOS)', value: 'square' },
        { labelKey: 'Прямоугольные вертикальные (Постеры)', value: 'rectangle-vertical' },
        { labelKey: 'Круглые (Иконки)', value: 'circle' },
        { labelKey: 'Капсулы (Компактные пилюли)', value: 'pill' },
      ],
    },
    {
      key: 'tileSize',
      labelKey: 'Размер закладок',
      type: 'select',
      defaultValue: 'medium',
      options: [
        { labelKey: 'Мини (Extra Small)', value: 'xs' },
        { labelKey: 'Компактный (Small)', value: 'compact' },
        { labelKey: 'Стандартный (Medium)', value: 'medium' },
        { labelKey: 'Крупный (Large)', value: 'large' },
        { labelKey: 'Максимальный (Extra Large)', value: 'xl' },
      ],
    },
    {
      key: 'cardStyle',
      labelKey: 'Стиль подложки карточек',
      type: 'select',
      defaultValue: 'glass',
      options: [
        { labelKey: 'Стеклянный полупрозрачный (Glassmorphism)', value: 'glass' },
        { labelKey: 'Сплошной плотный (Solid Surface)', value: 'solid' },
        { labelKey: 'Контурный (Outline Border)', value: 'outline' },
        { labelKey: 'Прозрачный (Без фона)', value: 'transparent' },
        { labelKey: 'Неоновое свечение (Glow Accent)', value: 'glow' },
      ],
    },
    {
      key: 'borderRadius',
      labelKey: 'Скругление углов',
      type: 'select',
      defaultValue: 'md',
      options: [
        { labelKey: 'Прямые углы (0px)', value: 'none' },
        { labelKey: 'Легкое скругление (8px)', value: 'sm' },
        { labelKey: 'Среднее скругление (14px)', value: 'md' },
        { labelKey: 'Большое скругление (20px)', value: 'lg' },
        { labelKey: 'Полное скругление (Pill / Circle)', value: 'full' },
      ],
    },
    {
      key: 'hoverEffect',
      labelKey: 'Эффект при наведении',
      type: 'select',
      defaultValue: 'scale',
      options: [
        { labelKey: 'Плавное увеличение (Scale Zoom)', value: 'scale' },
        { labelKey: 'Приподнятие с тенью (Lift Elevation)', value: 'lift' },
        { labelKey: 'Неоновая подсветка (Glow Aura)', value: 'glow' },
        { labelKey: 'Подсветка рамки (Border Highlight)', value: 'border' },
        { labelKey: 'Без эффекта', value: 'none' },
      ],
    },
    {
      key: 'columns',
      labelKey: 'Количество колонок в сетке',
      type: 'select',
      defaultValue: 'auto',
      options: [
        { labelKey: 'Автоматически (Адаптивно)', value: 'auto' },
        { labelKey: '1 колонка', value: 1 },
        { labelKey: '2 колонки', value: 2 },
        { labelKey: '3 колонки', value: 3 },
        { labelKey: '4 колонки', value: 4 },
        { labelKey: '5 колонок', value: 5 },
        { labelKey: '6 колонок', value: 6 },
      ],
    },
    {
      key: 'showTitle',
      labelKey: 'Показывать название сайта',
      type: 'boolean',
      defaultValue: true,
    },
    {
      key: 'showUrl',
      labelKey: 'Показывать URL / домен сайта',
      type: 'boolean',
      defaultValue: true,
    },
    {
      key: 'showIcon',
      labelKey: 'Показывать фавикон / иконку',
      type: 'boolean',
      defaultValue: true,
    },
    {
      key: 'structureMode',
      labelKey: 'Отображение подпапок',
      type: 'select',
      defaultValue: 'tree',
      options: [
        { labelKey: 'Иерархическая структура (с переходом по папкам)', value: 'tree' },
        { labelKey: 'Единый плоский список (все закладки без вложенности)', value: 'flatten' },
      ],
    },
    {
      key: 'folderSource',
      labelKey: 'Источник данных',
      type: 'select',
      defaultValue: 'chrome',
      options: [
        { labelKey: 'Закладки Chrome', value: 'chrome' },
        { labelKey: 'Кастомный список DashFlow', value: 'custom' },
      ],
    },
    {
      key: 'singleTitle',
      labelKey: 'Название сайта (для одиночного)',
      type: 'text',
      defaultValue: 'Google',
    },
    {
      key: 'singleUrl',
      labelKey: 'URL адрес (для одиночного)',
      type: 'text',
      defaultValue: 'https://google.com',
    },
    {
      key: 'openInNewTab',
      labelKey: 'Открывать в новой вкладке',
      type: 'boolean',
      defaultValue: true,
    },
    {
      key: 'showSearch',
      labelKey: 'Показывать строку поиска',
      type: 'boolean',
      defaultValue: true,
    },
  ],
  load: () => import('./BookmarksWidget').then((m) => ({ default: m.BookmarksWidget })),
};
