import type { WidgetDefinition } from '@/core/widget';
import type { BookmarkSettings } from './types';

export const bookmarksManifest: WidgetDefinition<BookmarkSettings> = {
  id: 'bookmarks',
  nameKey: 'widgets.bookmarks',
  descriptionKey: 'widgetDesc.bookmarks',
  version: '3.1.0',
  iconName: 'Bookmark',
  category: 'productivity',
  surface: 'tiles',
  permissions: ['bookmarks'],
  size: {
    defaultW: 6,
    defaultH: 4,
    minW: 1,
    minH: 1,
  },
  settingsSchema: [
    {
      key: 'mode',
      labelKey: 'Режим отображения',
      type: 'segmented',
      defaultValue: 'folder',
      section: 'appearance',
      helperText: 'Папка закладок браузера, одиночный крупный тайл сайта или мульти-вкладки',
      options: [
        { labelKey: 'Папка закладок', value: 'folder' },
        { labelKey: 'Одиночный сайт', value: 'single' },
        { labelKey: 'Сайты + Вкладки', value: 'folder-tabs' },
      ],
    },
    {
      key: 'tileShape',
      labelKey: 'Форма закладок',
      type: 'segmented',
      defaultValue: 'rectangle-horizontal',
      section: 'appearance',
      helperText: 'Геометрический силуэт плиток: карточки, квадратный Speed Dial, постеры или круглые иконки',
      options: [
        { labelKey: 'Карточка', value: 'rectangle-horizontal' },
        { labelKey: 'Квадрат', value: 'square' },
        { labelKey: 'Постер', value: 'rectangle-vertical' },
        { labelKey: 'Круг', value: 'circle' },
      ],
    },
    {
      key: 'cardStyle',
      labelKey: 'Стиль подложки карточек',
      type: 'select',
      defaultValue: 'glass',
      section: 'appearance',
      helperText: 'Материал и заливка фона: стекло, сплошной, контур или свечение',
      options: [
        { labelKey: 'Стеклянный (Glassmorphism)', value: 'glass' },
        { labelKey: 'Сплошной (Solid)', value: 'solid' },
        { labelKey: 'Контурный (Outline)', value: 'outline' },
        { labelKey: 'Прозрачный', value: 'transparent' },
        { labelKey: 'Неоновое свечение (Glow)', value: 'glow' },
      ],
    },
    {
      key: 'borderRadius',
      labelKey: 'Скругление углов',
      type: 'select',
      defaultValue: 'md',
      section: 'appearance',
      helperText: 'Радиус скругления углов плиток',
      options: [
        { labelKey: 'Прямые углы (0px)', value: 'none' },
        { labelKey: 'Легкое (8px)', value: 'sm' },
        { labelKey: 'Среднее (14px)', value: 'md' },
        { labelKey: 'Большое (20px)', value: 'lg' },
        { labelKey: 'Полное (Pill/Circle)', value: 'full' },
      ],
    },
    {
      key: 'tileSize',
      labelKey: 'Размер плиток',
      type: 'select',
      defaultValue: 'medium',
      section: 'appearance',
      helperText: 'Масштаб плиток закладок',
      options: [
        { labelKey: 'Мини (XS)', value: 'xs' },
        { labelKey: 'Компактный (Small)', value: 'compact' },
        { labelKey: 'Стандартный (Medium)', value: 'medium' },
        { labelKey: 'Крупный (Large)', value: 'large' },
        { labelKey: 'Максимальный (XL)', value: 'xl' },
      ],
    },
    {
      key: 'columns',
      labelKey: 'Количество колонок в сетке',
      type: 'select',
      defaultValue: 'auto',
      section: 'appearance',
      helperText: 'Количество столбцов или авто-адаптация под размер контейнера',
      options: [
        { labelKey: 'Автоматически', value: 'auto' },
        { labelKey: '1 колонка', value: 1 },
        { labelKey: '2 колонки', value: 2 },
        { labelKey: '3 колонки', value: 3 },
        { labelKey: '4 колонки', value: 4 },
        { labelKey: '5 колонок', value: 5 },
        { labelKey: '6 колонок', value: 6 },
      ],
    },
    {
      key: 'showSearch',
      labelKey: 'Строка живого поиска',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Быстрый поиск и фильтрация закладок по названию и URL',
    },
    {
      key: 'showTitle',
      labelKey: 'Показывать название сайта',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Текстовое имя закладки',
    },
    {
      key: 'showUrl',
      labelKey: 'Показывать URL / домен сайта',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Вывод доменного имени под названием',
    },
    {
      key: 'showIcon',
      labelKey: 'Показывать фавикон',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Логотип веб-ресурса высокого разрешения',
    },
    {
      key: 'structureMode',
      labelKey: 'Отображение подпапок',
      type: 'select',
      defaultValue: 'tree',
      section: 'behavior',
      helperText: 'Навигация с переходом вглубь папок или сквозной плоский список всех ссылок',
      options: [
        { labelKey: 'Иерархическая структура (дерево папок)', value: 'tree' },
        { labelKey: 'Единый плоский список (без папок)', value: 'flatten' },
      ],
    },
    {
      key: 'folderSource',
      labelKey: 'Источник закладок',
      type: 'segmented',
      defaultValue: 'chrome',
      section: 'data',
      helperText: 'Системные закладки браузера или персональный список DashFlow',
      options: [
        { labelKey: 'Браузер', value: 'chrome' },
        { labelKey: 'Кастомный', value: 'custom' },
      ],
    },
    {
      key: 'openInNewTab',
      labelKey: 'Открывать в новой вкладке',
      type: 'boolean',
      defaultValue: true,
      section: 'behavior',
      helperText: 'Открывать сайт в новой вкладке браузера',
    },
  ],
  load: () => import('./BookmarksWidget').then((m) => ({ default: m.BookmarksWidget })),
};
