import type { WidgetDefinition } from '@/core/widget';
import type { ClockSettings } from './types';

export const clockManifest: WidgetDefinition<ClockSettings> = {
  id: 'clock',
  nameKey: 'widgets.clock',
  descriptionKey: 'widgetDesc.clock',
  version: '3.0.0',
  iconName: 'Clock',
  category: 'hero',
  surface: 'chromeless',
  size: {
    defaultW: 4,
    defaultH: 2,
    minW: 3,
    minH: 2,
  },
  settingsSchema: [
    {
      key: 'clockStyle',
      labelKey: 'Стиль циферблата',
      type: 'segmented',
      defaultValue: 'digital',
      section: 'appearance',
      helperText: 'Выберите визуальный стиль шрифта и оформления цифр',
      options: [
        { labelKey: 'Digital', value: 'digital' },
        { labelKey: 'Flip', value: 'flip' },
        { labelKey: 'Serif', value: 'serif' },
        { labelKey: 'Mono', value: 'mono' },
        { labelKey: 'Minimal', value: 'minimal' },
      ],
    },
    {
      key: 'glowEffect',
      labelKey: 'Неоновое свечение (Glow)',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Мягкий атмосферный ореол вокруг цифр',
    },
    {
      key: 'is24Hour',
      labelKey: '24-часовой формат времени',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Отображение времени в формате 24ч или 12ч (AM/PM)',
    },
    {
      key: 'showSeconds',
      labelKey: 'Показывать секунды',
      type: 'boolean',
      defaultValue: false,
      section: 'appearance',
      helperText: 'Отображение бегущих секунд рядом с минутами',
    },
    {
      key: 'blinkColon',
      labelKey: 'Пульсирующее двоеточие',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Мигание разделителя секунд в такт секундам',
    },
    {
      key: 'showDate',
      labelKey: 'Показывать дату и день недели',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Вывод сегодняшней даты под часами',
    },
    {
      key: 'dateFormat',
      labelKey: 'Формат даты',
      type: 'select',
      defaultValue: 'full',
      section: 'appearance',
      helperText: 'Степень подробности отображения дня и месяца',
      options: [
        { labelKey: 'Полный (Понедельник, 3 сентября)', value: 'full' },
        { labelKey: 'Краткий (Пн, 3 сент.)', value: 'short' },
        { labelKey: 'Числовой (03.09)', value: 'numeric' },
      ],
    },
    {
      key: 'timezone',
      labelKey: 'Часовой пояс',
      type: 'select',
      defaultValue: 'local',
      section: 'behavior',
      helperText: 'Часовой пояс для расчета времени (удобно для удаленной работы)',
      options: [
        { labelKey: 'Текущее локальное время устройства', value: 'local' },
        { labelKey: 'UTC (Всемирное координированное)', value: 'UTC' },
        { labelKey: 'Лондон (GMT/BST)', value: 'Europe/London' },
        { labelKey: 'Берлин / Париж (CET)', value: 'Europe/Berlin' },
        { labelKey: 'Москва / Стамбул (MSK)', value: 'Europe/Moscow' },
        { labelKey: 'Дубай (GST)', value: 'Asia/Dubai' },
        { labelKey: 'Нью-Йорк (EST/EDT)', value: 'America/New_York' },
        { labelKey: 'Сан-Франциско (PST/PDT)', value: 'America/Los_Angeles' },
        { labelKey: 'Токио (JST)', value: 'Asia/Tokyo' },
      ],
    },
    {
      key: 'showGreeting',
      labelKey: 'Персональное приветствие',
      type: 'boolean',
      defaultValue: false,
      section: 'behavior',
      helperText: 'Приветствие по времени суток над часами',
    },
    {
      key: 'userName',
      labelKey: 'Имя пользователя',
      type: 'text',
      placeholder: 'Denis',
      defaultValue: '',
      section: 'behavior',
      helperText: 'Имя, отображаемое в тексте приветствия',
    },
  ],
  load: () => import('./ClockWidget').then((m) => ({ default: m.ClockWidget })),
};
