// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/favicon.svg"
    | "/icon-128.png"
    | "/icon-16.png"
    | "/icon-32.png"
    | "/icon-48.png"
    | "/newtab.html"
    | "/opengraph.jpg"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
