import type { WidgetDefinition } from '@/core/widget';
import type { GreetingSettings } from './types';

export const greetingManifest: WidgetDefinition<GreetingSettings> = {
  id: 'greeting',
  nameKey: 'widgets.greeting',
  descriptionKey: 'widgetDesc.greeting',
  version: '1.0.0',
  iconName: 'Sparkles',
  category: 'hero',
  surface: 'chromeless',
  size: {
    defaultW: 4,
    defaultH: 2,
    minW: 2,
    minH: 1,
  },
  settingsSchema: [
    {
      key: 'userName',
      labelKey: 'Имя пользователя',
      type: 'text',
      placeholder: 'Denis',
      defaultValue: '',
      section: 'behavior',
      helperText: 'Имя, подставляемое в текст персонального приветствия',
    },
    {
      key: 'customGreeting',
      labelKey: 'Свой текст приветствия',
      type: 'text',
      placeholder: 'Например: Приветствую, Создатель!',
      defaultValue: '',
      section: 'behavior',
      helperText: 'Переопределить стандартное приветствие по времени суток',
    },
    {
      key: 'motivationalStatus',
      labelKey: 'Мотивационный статус',
      type: 'text',
      placeholder: 'Готов покорять вершины',
      defaultValue: '',
      section: 'behavior',
      helperText: 'Текст вдохновляющего девиза под именем',
    },
    {
      key: 'fontSize',
      labelKey: 'Размер заголовка',
      type: 'segmented',
      defaultValue: 'lg',
      section: 'appearance',
      helperText: 'Масштаб шрифта текста приветствия',
      options: [
        { labelKey: 'S', value: 'sm' },
        { labelKey: 'M', value: 'md' },
        { labelKey: 'L', value: 'lg' },
        { labelKey: 'XL', value: 'xl' },
      ],
    },
    {
      key: 'align',
      labelKey: 'Выравнивание',
      type: 'segmented',
      defaultValue: 'center',
      section: 'appearance',
      helperText: 'Позиция текста в карточке виджета',
      options: [
        { labelKey: 'Слева', value: 'left' },
        { labelKey: 'По центру', value: 'center' },
        { labelKey: 'Справа', value: 'right' },
      ],
    },
    {
      key: 'glowEffect',
      labelKey: 'Атмосферное свечение текста',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Мягкий неоновый ореол вокруг приветствия',
    },
    {
      key: 'showIcon',
      labelKey: 'Эмодзи времени суток',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Показывать иконку (солнце, рассвет, луна) рядом со словами',
    },
  ],
  load: () => import('./GreetingWidget').then((m) => ({ default: m.GreetingWidget })),
};
