import type { WidgetDefinition } from '@/core/widget';
import type { NotesSettings } from './types';

export const notesManifest: WidgetDefinition<NotesSettings> = {
  id: 'notes',
  nameKey: 'widgets.notes',
  descriptionKey: 'widgetDesc.notes',
  version: '2.5.0',
  iconName: 'FileText',
  category: 'productivity',
  surface: 'panel',
  permissions: ['storage'],
  size: {
    defaultW: 6,
    defaultH: 4,
    minW: 4,
    minH: 3,
  },
  settingsSchema: [
    {
      key: 'defaultMode',
      labelKey: 'Режим по умолчанию',
      type: 'segmented',
      defaultValue: 'edit',
      section: 'behavior',
      helperText: 'Режим при открытии заметки: редактирование текста или рендер Markdown',
      options: [
        { labelKey: 'Редактор', value: 'edit' },
        { labelKey: 'Markdown', value: 'preview' },
      ],
    },
    {
      key: 'fontFamily',
      labelKey: 'Гарнитура шрифта',
      type: 'segmented',
      defaultValue: 'sans',
      section: 'appearance',
      helperText: 'Стиль шрифта: гротеск Inter, моноширинный для кода или элегантный с засечками',
      options: [
        { labelKey: 'Sans', value: 'sans' },
        { labelKey: 'Code (Mono)', value: 'mono' },
        { labelKey: 'Serif', value: 'serif' },
      ],
    },
    {
      key: 'fontSize',
      labelKey: 'Размер шрифта',
      type: 'slider',
      defaultValue: 13,
      min: 11,
      max: 20,
      step: 1,
      unit: 'px',
      section: 'appearance',
      helperText: 'Размер кегля текста заметки',
    },
    {
      key: 'lineWrapping',
      labelKey: 'Автоперенос длинных строк',
      type: 'boolean',
      defaultValue: true,
      section: 'behavior',
      helperText: 'Переносить длинные строки или использовать горизонтальный скролл (удобно для кода)',
    },
    {
      key: 'showWordCount',
      labelKey: 'Счетчик слов и знаков',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Индикатор объема текста в нижней строке виджета',
    },
    {
      key: 'showSaveStatus',
      labelKey: 'Индикатор автосохранения',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Статус синхронизации с локальным хранилищем в реальном времени',
    },
  ],
  load: () => import('./NotesWidget').then((m) => ({ default: m.NotesWidget })),
};
