import type { WidgetDefinition } from '@/core/widget';
import type { IframeSettings } from './types';

export const iframeManifest: WidgetDefinition<IframeSettings> = {
  id: 'iframe',
  nameKey: 'widgets.iframe',
  descriptionKey: 'widgetDesc.iframe',
  version: '2.5.0',
  iconName: 'Globe',
  category: 'utilities',
  surface: 'panel',
  permissions: ['network'],
  size: {
    defaultW: 6,
    defaultH: 4,
    minW: 4,
    minH: 3,
  },
  settingsSchema: [
    {
      key: 'url',
      labelKey: 'URL адрес страницы',
      type: 'text',
      defaultValue: 'https://wxt.dev',
      section: 'data',
      placeholder: 'https://...',
      helperText: 'Веб-страница для встраивания (сайт должен разрешать iframe через X-Frame-Options)',
    },
    {
      key: 'title',
      labelKey: 'Заголовок фрейма',
      type: 'text',
      defaultValue: '',
      placeholder: 'Дашборд аналитики / Плеер',
      section: 'appearance',
      helperText: 'Пользовательское название в шапке фрейма',
    },
    {
      key: 'showToolbar',
      labelKey: 'Панель инструментов (URL, Обновить, Вкладка)',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Тонкая верхняя плашка с кнопками перезагрузки и перехода',
    },
    {
      key: 'zoom',
      labelKey: 'Масштаб страницы (%)',
      type: 'slider',
      defaultValue: 100,
      min: 50,
      max: 150,
      step: 5,
      unit: '%',
      section: 'appearance',
      helperText: 'CSS-масштабирование контента внутри встроенного окна',
    },
    {
      key: 'allowScroll',
      labelKey: 'Разрешить прокрутку фрейма',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Отображение полос скролла при выходе за границы',
    },
  ],
  load: () => import('./IframeWidget').then((m) => ({ default: m.IframeWidget })),
};
