import type { WidgetDefinition } from '@/core/widget';
import type { SearchSettings } from './types';

export const searchManifest: WidgetDefinition<SearchSettings> = {
  id: 'search',
  nameKey: 'widgets.search',
  descriptionKey: 'widgetDesc.search',
  version: '3.0.0',
  iconName: 'Search',
  category: 'hero',
  surface: 'chromeless',
  size: {
    defaultW: 6,
    defaultH: 2,
    minW: 4,
    minH: 2,
  },
  settingsSchema: [
    {
      key: 'searchStyle',
      labelKey: 'Стиль поисковой строки',
      type: 'segmented',
      defaultValue: 'bar',
      section: 'appearance',
      helperText: 'Стильная парящая капсула или классические плитки провайдеров',
      options: [
        { labelKey: 'Капсула', value: 'bar' },
        { labelKey: 'Плитки', value: 'tiles' },
      ],
    },
    {
      key: 'engine',
      labelKey: 'Поисковая система по умолчанию',
      type: 'select',
      defaultValue: 'google',
      section: 'behavior',
      helperText: 'Основной поисковый движок для быстрых запросов',
      options: [
        { labelKey: 'Google', value: 'google' },
        { labelKey: 'Яндекс', value: 'yandex' },
        { labelKey: 'DuckDuckGo (Конфиденциальный)', value: 'duckduckgo' },
        { labelKey: 'Brave Search', value: 'brave' },
        { labelKey: 'Microsoft Bing', value: 'bing' },
        { labelKey: 'Perplexity AI', value: 'perplexity' },
        { labelKey: 'ChatGPT', value: 'chatgpt' },
        { labelKey: 'Claude AI', value: 'claude' },
        { labelKey: 'GitHub Code Search', value: 'github' },
        { labelKey: 'YouTube Video', value: 'youtube' },
      ],
    },
    {
      key: 'showEngineSelector',
      labelKey: 'Быстрое переключение поисковика',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Отображение иконки поисковика с меню смены прямо в строке',
    },
    {
      key: 'showHotkeyBadge',
      labelKey: 'Подсказка горячей клавиши [/]',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Отображать бейдж быстрой активации поиска клавишей слеш',
    },
    {
      key: 'placeholder',
      labelKey: 'Текст подсказки (Placeholder)',
      type: 'text',
      defaultValue: '',
      placeholder: 'Искать в интернете или ввести URL...',
      section: 'appearance',
      helperText: 'Пользовательский текст в пустой строке поиска',
    },
    {
      key: 'openInNewTab',
      labelKey: 'Открывать результаты в новой вкладке',
      type: 'boolean',
      defaultValue: false,
      section: 'behavior',
      helperText: 'Сохранять текущую страницу дашборда при переходе к поиску',
    },
    {
      key: 'autoFocus',
      labelKey: 'Автофокус при открытии вкладки',
      type: 'boolean',
      defaultValue: false,
      section: 'behavior',
      helperText: 'Автоматически устанавливать курсор в поле поиска при старте',
    },
  ],
  load: () => import('./SearchWidget').then((m) => ({ default: m.SearchWidget })),
};
