import type { WidgetDefinition } from '@/core/widget';
import type { RssSettings } from './types';

export const rssManifest: WidgetDefinition<RssSettings> = {
  id: 'rssReader',
  nameKey: 'widgets.rssReader',
  descriptionKey: 'widgetDesc.rssReader',
  version: '3.2.0',
  iconName: 'Rss',
  category: 'news',
  surface: 'panel',
  permissions: ['network', 'storage'],
  size: {
    defaultW: 6,
    defaultH: 4,
    minW: 3,
    minH: 2,
  },
  settingsSchema: [
    {
      key: 'readingMode',
      labelKey: 'Режим чтения',
      type: 'select',
      defaultValue: 'unified',
      options: [
        { labelKey: 'Единая хронологическая лента (Все новости)', value: 'unified' },
        { labelKey: 'По отдельным источникам (Вкладки)', value: 'feed-tabs' },
        { labelKey: 'По папкам и тематикам (Категории)', value: 'folders' },
      ],
    },
    {
      key: 'viewMode',
      labelKey: 'Макет отображения новостей',
      type: 'select',
      defaultValue: 'thumbnails',
      options: [
        { labelKey: 'С миниатюрами (картинка слева)', value: 'thumbnails' },
        { labelKey: 'Компактный строчный список', value: 'compact' },
        { labelKey: 'Крупные карточки с описанием', value: 'cards' },
        { labelKey: 'Адаптивная сетка (2 колонки)', value: 'grid' },
        { labelKey: 'Журнальный (главная новость + список)', value: 'magazine' },
      ],
    },
    {
      key: 'cardStyle',
      labelKey: 'Стиль подложки карточек',
      type: 'select',
      defaultValue: 'glass',
      options: [
        { labelKey: 'Стекло (Glassmorphism)', value: 'glass' },
        { labelKey: 'Сплошной цвет (Solid)', value: 'solid' },
        { labelKey: 'Контурная рамка (Outline)', value: 'outline' },
        { labelKey: 'Прозрачный', value: 'transparent' },
      ],
    },
    {
      key: 'borderRadius',
      labelKey: 'Скругление углов',
      type: 'select',
      defaultValue: 'md',
      options: [
        { labelKey: 'Без скругления', value: 'none' },
        { labelKey: 'Малое (SM)', value: 'sm' },
        { labelKey: 'Среднее (MD)', value: 'md' },
        { labelKey: 'Большое (LG)', value: 'lg' },
      ],
    },
    {
      key: 'itemCount',
      labelKey: 'Количество новостей на источник',
      type: 'slider',
      defaultValue: 15,
      min: 3,
      max: 50,
      step: 1,
    },
    {
      key: 'refreshInterval',
      labelKey: 'Интервал автообновления (минут)',
      type: 'select',
      defaultValue: 30,
      options: [
        { labelKey: 'Только вручную', value: 0 },
        { labelKey: 'Каждые 15 минут', value: 15 },
        { labelKey: 'Каждые 30 минут', value: 30 },
        { labelKey: 'Каждый час', value: 60 },
        { labelKey: 'Каждые 6 часов', value: 360 },
      ],
    },
    {
      key: 'showThumbnails',
      labelKey: 'Показывать миниатюры (изображения)',
      type: 'boolean',
      defaultValue: true,
    },
    {
      key: 'showDescription',
      labelKey: 'Показывать краткое описание новости',
      type: 'boolean',
      defaultValue: true,
    },
    {
      key: 'showSource',
      labelKey: 'Показывать название источника',
      type: 'boolean',
      defaultValue: true,
    },
    {
      key: 'showDate',
      labelKey: 'Показывать дату/время публикации',
      type: 'boolean',
      defaultValue: true,
    },
    {
      key: 'showSearch',
      labelKey: 'Показывать строку быстрого поиска',
      type: 'boolean',
      defaultValue: true,
    },
    {
      key: 'openInNewTab',
      labelKey: 'Открывать новость в новой вкладке',
      type: 'boolean',
      defaultValue: true,
    },
  ],
  load: () => import('./RssWidget').then((m) => ({ default: m.RssWidget })),
};
