import type { WidgetDefinition } from '@/core/widget';
import type { RssSettings } from './types';

export const rssManifest: WidgetDefinition<RssSettings> = {
  id: 'rssReader',
  nameKey: 'widgets.rssReader',
  descriptionKey: 'widgetDesc.rssReader',
  version: '3.2.0',
  iconName: 'Rss',
  category: 'news',
  surface: 'panel',
  permissions: ['network', 'storage'],
  size: {
    defaultW: 6,
    defaultH: 4,
    minW: 3,
    minH: 2,
  },
  settingsSchema: [
    {
      key: 'readingMode',
      labelKey: 'Режим чтения',
      type: 'segmented',
      defaultValue: 'unified',
      section: 'appearance',
      helperText: 'Единая сквозная лента или фильтрация по вкладкам и папкам',
      options: [
        { labelKey: 'Единая лента', value: 'unified' },
        { labelKey: 'Вкладки', value: 'feed-tabs' },
        { labelKey: 'Категории', value: 'folders' },
      ],
    },
    {
      key: 'viewMode',
      labelKey: 'Макет отображения новостей',
      type: 'select',
      defaultValue: 'thumbnails',
      section: 'appearance',
      helperText: 'Визуальный формат списка: миниатюры, компактные строки или крупные карточки',
      options: [
        { labelKey: 'С миниатюрами (картинка слева)', value: 'thumbnails' },
        { labelKey: 'Компактный строчный список', value: 'compact' },
        { labelKey: 'Крупные карточки с описанием', value: 'cards' },
        { labelKey: 'Адаптивная сетка (2 колонки)', value: 'grid' },
        { labelKey: 'Журнальный (главная новость + список)', value: 'magazine' },
      ],
    },
    {
      key: 'cardStyle',
      labelKey: 'Стиль карточек',
      type: 'select',
      defaultValue: 'glass',
      section: 'appearance',
      helperText: 'Степень прозрачности и материал карточек ленты',
      options: [
        { labelKey: 'Стекло (Glassmorphism)', value: 'glass' },
        { labelKey: 'Сплошной (Solid)', value: 'solid' },
        { labelKey: 'Контурная рамка (Outline)', value: 'outline' },
        { labelKey: 'Прозрачный', value: 'transparent' },
      ],
    },
    {
      key: 'itemCount',
      labelKey: 'Лимит новостей на источник',
      type: 'slider',
      defaultValue: 15,
      min: 3,
      max: 50,
      step: 1,
      section: 'behavior',
      helperText: 'Максимальное количество загружаемых публикаций',
    },
    {
      key: 'refreshInterval',
      labelKey: 'Интервал автообновления',
      type: 'select',
      defaultValue: 30,
      section: 'behavior',
      helperText: 'Частота фоновой проверки свежих статей ленты',
      options: [
        { labelKey: 'Только вручную', value: 0 },
        { labelKey: 'Каждые 15 минут', value: 15 },
        { labelKey: 'Каждые 30 минут', value: 30 },
        { labelKey: 'Каждый час', value: 60 },
        { labelKey: 'Каждые 6 часов', value: 360 },
      ],
    },
    {
      key: 'showThumbnails',
      labelKey: 'Показывать миниатюры (изображения)',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Загружать и выводить обложки статей',
    },
    {
      key: 'showDescription',
      labelKey: 'Краткое описание публикации',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Показывать вводный абзац новости',
    },
    {
      key: 'showSource',
      labelKey: 'Название источника (издания)',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Бейдж с именем веб-сайта или RSS-канала',
    },
    {
      key: 'showSearch',
      labelKey: 'Строка живого поиска',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Быстрый поиск статей прямо внутри виджета',
    },
    {
      key: 'openInNewTab',
      labelKey: 'Открывать новость в новой вкладке',
      type: 'boolean',
      defaultValue: true,
      section: 'behavior',
      helperText: 'Переходить к полной статье во внешней вкладке',
    },
  ],
  load: () => import('./RssWidget').then((m) => ({ default: m.RssWidget })),
};
