import type { WidgetDefinition } from '@/core/widget';
import type { PomodoroSettings } from './types';

export const pomodoroManifest: WidgetDefinition<PomodoroSettings> = {
  id: 'pomodoro',
  nameKey: 'widgets.pomodoro',
  descriptionKey: 'widgetDesc.pomodoro',
  version: '2.5.0',
  iconName: 'Flame',
  category: 'productivity',
  surface: 'panel',
  permissions: ['storage'],
  size: {
    defaultW: 4,
    defaultH: 3,
    minW: 3,
    minH: 2,
  },
  settingsSchema: [
    {
      key: 'timerStyle',
      labelKey: 'Стиль визуализации',
      type: 'segmented',
      defaultValue: 'ring',
      section: 'appearance',
      helperText: 'Круговой светящийся прогресс-бар или крупные минималистичные цифры',
      options: [
        { labelKey: 'Кольцо', value: 'ring' },
        { labelKey: 'Цифры', value: 'digital' },
      ],
    },
    {
      key: 'workTime',
      labelKey: 'Время фокуса',
      type: 'slider',
      defaultValue: 25,
      min: 1,
      max: 60,
      step: 1,
      unit: 'мин',
      section: 'behavior',
      helperText: 'Длительность интервала глубокой работы',
    },
    {
      key: 'breakTime',
      labelKey: 'Короткий перерыв',
      type: 'slider',
      defaultValue: 5,
      min: 1,
      max: 30,
      step: 1,
      unit: 'мин',
      section: 'behavior',
      helperText: 'Отдых между сессиями фокуса',
    },
    {
      key: 'longBreakTime',
      labelKey: 'Длинный перерыв',
      type: 'slider',
      defaultValue: 15,
      min: 5,
      max: 45,
      step: 1,
      unit: 'мин',
      section: 'behavior',
      helperText: 'Глубокий отдых после завершения цикла из 4 сессий',
    },
    {
      key: 'autoStartBreaks',
      labelKey: 'Автоматический старт перерывов',
      type: 'boolean',
      defaultValue: false,
      section: 'behavior',
      helperText: 'Автоматически запускать отсчет отдыха по истечении рабочего спринта',
    },
    {
      key: 'soundEnabled',
      labelKey: 'Звуковое оповещение',
      type: 'boolean',
      defaultValue: true,
      section: 'behavior',
      helperText: 'Мягкий сигнал Web Audio API при смене фазы таймера',
    },
  ],
  load: () => import('./PomodoroWidget').then((m) => ({ default: m.PomodoroWidget })),
};
