// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/newtab-dashboard/NewTabDashboard.tsx": () => import("../components/mockups/newtab-dashboard/NewTabDashboard.tsx")
};
