import type { WidgetDefinition } from '@/core/widget';
import type { TodoSettings } from './types';

export const todoManifest: WidgetDefinition<TodoSettings> = {
  id: 'todo',
  nameKey: 'widgets.todo',
  descriptionKey: 'widgetDesc.todo',
  version: '2.5.0',
  iconName: 'CheckSquare',
  category: 'productivity',
  surface: 'panel',
  permissions: ['storage'],
  size: {
    defaultW: 6,
    defaultH: 4,
    minW: 4,
    minH: 3,
  },
  settingsSchema: [
    {
      key: 'defaultTab',
      labelKey: 'Вкладка по умолчанию',
      type: 'segmented',
      defaultValue: 'todos',
      section: 'behavior',
      helperText: 'Стартовый раздел при открытии вкладки: список задач или трекер привычек',
      options: [
        { labelKey: 'Задачи', value: 'todos' },
        { labelKey: 'Привычки', value: 'habits' },
      ],
    },
    {
      key: 'sortBy',
      labelKey: 'Сортировка задач',
      type: 'select',
      defaultValue: 'date',
      section: 'behavior',
      helperText: 'Порядок расположения задач в списке',
      options: [
        { labelKey: 'По дате добавления (новые сверху)', value: 'date' },
        { labelKey: 'По приоритету (High → Low)', value: 'priority' },
        { labelKey: 'По алфавиту (А-Я)', value: 'text' },
      ],
    },
    {
      key: 'filter',
      labelKey: 'Фильтр отображения',
      type: 'select',
      defaultValue: 'all',
      section: 'behavior',
      helperText: 'Какие задачи показывать в списке по умолчанию',
      options: [
        { labelKey: 'Все задачи', value: 'all' },
        { labelKey: 'Только активные', value: 'active' },
        { labelKey: 'Только завершенные', value: 'completed' },
      ],
    },
    {
      key: 'hideCompleted',
      labelKey: 'Скрывать выполненные задачи',
      type: 'boolean',
      defaultValue: false,
      section: 'behavior',
      helperText: 'Автоматически убирать завершенные задачи из активного списка',
    },
    {
      key: 'defaultPriority',
      labelKey: 'Приоритет новой задачи',
      type: 'select',
      defaultValue: 'medium',
      section: 'behavior',
      helperText: 'Начальный приоритет при быстром добавлении задачи',
      options: [
        { labelKey: 'Низкий (Low)', value: 'low' },
        { labelKey: 'Средний (Medium)', value: 'medium' },
        { labelKey: 'Высокий (High)', value: 'high' },
      ],
    },
    {
      key: 'showProgress',
      labelKey: 'Прогресс-бар выполнения дня',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Отображать процент и шкалу завершенности всех задач',
    },
    {
      key: 'density',
      labelKey: 'Плотность списка',
      type: 'segmented',
      defaultValue: 'comfortable',
      section: 'appearance',
      helperText: 'Компактный размер для большого количества задач или комфортный',
      options: [
        { labelKey: 'Комфортная', value: 'comfortable' },
        { labelKey: 'Компактная', value: 'compact' },
      ],
    },
  ],
  load: () => import('./TodoWidget').then((m) => ({ default: m.TodoWidget })),
};
