import type { WidgetDefinition } from '@/core/widget';
import type { WeatherSettings } from './types';

export const weatherManifest: WidgetDefinition<WeatherSettings> = {
  id: 'weather',
  nameKey: 'widgets.weather',
  descriptionKey: 'widgetDesc.weather',
  version: '3.7.0',
  iconName: 'CloudSun',
  category: 'utilities',
  surface: 'panel',
  permissions: ['network', 'storage', 'geolocation'],
  size: {
    defaultW: 4,
    defaultH: 2,
    minW: 2,
    minH: 2,
  },
  settingsSchema: [
    {
      key: 'city',
      labelKey: 'Город',
      type: 'text',
      defaultValue: 'Москва',
      section: 'data',
      helperText: 'Город для получения метеопрогноза Open-Meteo',
    },
    {
      key: 'viewMode',
      labelKey: 'Режим отображения',
      type: 'segmented',
      defaultValue: 'dashboard',
      section: 'appearance',
      helperText: 'Макет виджета: метеостанция, компактный или подробные таймлайны',
      options: [
        { labelKey: 'Метеостанция', value: 'dashboard' },
        { labelKey: 'Компактный', value: 'compact' },
        { labelKey: '24 часа', value: 'hourly' },
        { labelKey: '7 дней', value: 'weekly' },
      ],
    },
    {
      key: 'tempUnit',
      labelKey: 'Шкала температуры',
      type: 'segmented',
      defaultValue: 'celsius',
      section: 'appearance',
      helperText: 'Единицы измерения температуры воздуха',
      options: [
        { labelKey: '°C (Цельсий)', value: 'celsius' },
        { labelKey: '°F (Фаренгейт)', value: 'fahrenheit' },
      ],
    },
    {
      key: 'windSpeedUnit',
      labelKey: 'Скорость ветра',
      type: 'select',
      defaultValue: 'ms',
      section: 'data',
      helperText: 'Единицы измерения скорости ветра',
      options: [
        { labelKey: 'м/с (Метры в секунду)', value: 'ms' },
        { labelKey: 'км/ч (Километры в час)', value: 'kmh' },
        { labelKey: 'миль/ч (Мили в час)', value: 'mph' },
      ],
    },
    {
      key: 'pressureUnit',
      labelKey: 'Атмосферное давление',
      type: 'select',
      defaultValue: 'mmhg',
      section: 'data',
      helperText: 'Единицы измерения атмосферного давления',
      options: [
        { labelKey: 'мм рт. ст. (Миллиметры ртутного столба)', value: 'mmhg' },
        { labelKey: 'гПа (Гектопаскали / мбар)', value: 'hpa' },
      ],
    },
    {
      key: 'showMetrics',
      labelKey: 'Подробные метео-факторы',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Отображать карточки влажности, давления, ветра и УФ-индекса',
    },
    {
      key: 'showSunTimes',
      labelKey: 'Время восхода и заката',
      type: 'boolean',
      defaultValue: true,
      section: 'appearance',
      helperText: 'Отображать астрономическое время рассвета и сумерек',
    },
  ],
  load: () => import('./WeatherWidget').then((m) => ({ default: m.WeatherWidget })),
  loadSettings: () => import('./WeatherSettingsForm').then((m) => ({ default: m.WeatherSettingsForm })),
};
